@echo off
echo Deploying voting key...
sui client publish --gas-budget 10000 sources/voting_key.move
echo Deploying vote proof...
sui client publish --gas-budget 10000 sources/vote_proof.move
echo Deploying meme contract...
sui client publish --gas-budget 10000 sources/meme.move
echo Deploying contest contract...
sui client publish --gas-budget 10000 sources/contest.move
pause
